apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-server-deployment
  labels:
    app: python-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-server
  template:
    metadata:
      labels:
        app: python-server
    spec:
      containers:
      - name: python-server
        image: python-server:latest # Assuming you'll build and push this image
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: python-server-service
  labels:
    app: python-server
spec:
  selector:
    app: python-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP