apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice-ui-server-deployment
  labels:
    app: voice-ui-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voice-ui-server
  template:
    metadata:
      labels:
        app: voice-ui-server
    spec:
      containers:
      - name: voice-ui-server
        image: voice-ui-server:latest # Assuming you'll build and push this image
        ports:
        - containerPort: 8006
        env:
        - name: PORT
          value: "8006"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        volumeMounts:
        - name: dev-snd
          mountPath: /dev/snd
      volumes:
      - name: dev-snd
        hostPath:
          path: /dev/snd
---
apiVersion: v1
kind: Service
metadata:
  name: voice-ui-server-service
  labels:
    app: voice-ui-server
spec:
  selector:
    app: voice-ui-server
  ports:
    - protocol: TCP
      port: 8006
      targetPort: 8006
  type: ClusterIP